name: flight watcher

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  check-flight:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install packages
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python flight.py
